site_name: Victor's Resume
site_url: https://victormagalhaes/
repo_url: https://github.com/vitoiuo/curriculo-mkdocs
theme: 
  name: material
  palette:
    primary: black
    accent: white
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/victor-magalh%C3%A3es-barreto-ti/