site_name: Victor's Resume
site_url: https://victormagalhaes/
repo_url: https://github.com/vitoiuo/curriculo-mkdocs
theme: 
  name: material
  palette:
    primary: black
    accent: white
plugins:
  - search
  - enumerate-headings
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/squidfunk